CREATE TABLE IF NOT EXISTS APPROVALS (
    ID INT NOT NULL AUTO_INCREMENT,
    AUTHOR_ID VARCHAR(255) NOT NULL,
    TICKET_ID INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (TICKET_ID) REFERENCES TICKETS (ID)
);
