CREATE TABLE IF NOT EXISTS TICKETS (
    ID INT NOT NULL AUTO_INCREMENT,
    DESCRIPTION VARCHAR(255) NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID)
);
